global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100', 'sb-staging:9100', 'sb-prod:9100']

  - job_name: 'app_server'
    static_configs:
      - targets: ['sb-staging:80', 'sb-prod:80']

  - job_name: 'server_rs'
    static_configs:
      - targets: ['sb-staging:8001', 'sb-prod:8001']
